data_ingestion:
  bucket_name: "my_bucket5067"
  bucket_file_name: "Hotel_Reservations.csv"
  train_ratio: 0.8
  test_ratio: 0.2

data_processing:
  categorical_columns:
    - type_of_meal_plan
    - required_car_parking_space
    - room_type_reserved
    - market_segment_type
    - repeated_guest
    - booking_status
  numerical_columns:
    - arrival_date
    - arrival_month
    - arrival_year
    - avg_price_per_room
    - lead_time
    - no_of_adults
    - no_of_children
    - no_of_previous_bookings_not_canceled
    - no_of_previous_cancellations
    - no_of_special_requests
    - no_of_week_nights
    - no_of_weekend_nights
  skewness_threshold: 5